name: Checks

on:
   pull_request:

permissions:
   contents: read

jobs:
   verify:
      uses: ./.github/workflows/verify.yml
   packages:
      needs: verify
      uses: ./.github/workflows/package.yml
